{
 "title": "M5_forecasting",
 "description": "Here, we represents some metrics to monitor the developed model for predicting the sales for M5 dataset",
 "time": { "from": "2016-03-21T05:29:17.732Z", "to": "2016-04-28T02:51:08.419Z" },
 "panels": [
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "description": "It displays the number of drifted columns over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  num_drifted_columns\nFROM\n  dummy_metrics\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Mean Absolute Error",
   "type": "timeseries",
   "description": "It visualizes the mean absolute error values over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  mean_abs_error\nFROM\n  dummy_metrics\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Drift for Predictions and Target values",
   "type": "timeseries",
   "description": "here, we show the drift scores for both prediction and sales (target).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  prediction_drift\nFROM\n  dummy_metrics\nORDER BY\n  time"
    },
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  sales_drift\nFROM\n  dummy_metrics\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Drift for error values",
   "type": "timeseries",
   "description": "This shows the drift scores for error values (pred - true) over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  error_drift\nFROM\n  dummy_metrics\nORDER BY\n  time"
    }
   ]
  }
 ]
}