
volumes:
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier


  grafana:
    image: grafana/grafana-enterprise
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/opt/grafana/dashboards
    networks:
      - back-tier
      - front-tier
    restart: always
    
    
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring-deployment
    environment:
      PREFECT_API_URL: http://127.0.0.1:4200/api
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro   # ← Mount AWS credentials into container
    networks:
      - front-tier
      - back-tier
    ports:
      - "4200:4200"  # Prefect UI if launched from here

