
data:
  s3_bucket: 'data-bucket-m5'
  s3_reference_path: 'data/processed/reference_data.csv'
  s3_test_path: 'data/processed/test_data.csv'

mlflow:
  experiment_id: '1'
  run_id: "m-e53430983baf4cefad9573916a30a224"
  model_dir: 'models'
  creds_on: True


forecasting_period:
  start_forecasting_date: 1800
  how_many_days: 113 # how many days 


dashboards:
  dash_dir: "dashboards"
  config_file: "data_drift.json"

  db_name: 'test'
  table_name: 'dummy_metrics'
